import isEqual from 'lodash/isEqual';
import React from 'react';
import { ButtonTypes } from './Button.props';
import MUIButton from '@mui/material/Button';

const styles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  },
  containerStyle: {
    marginTop: '1em',
    marginBottom: '1em',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center'
  }
};

/**
 * Button is generated by Webcodesk. Replace this comment with a valuable description.
 */
class Button extends React.Component {
  constructor(props) {
    super(props);
    const { inputText, styling } = this.props;
    this.state = {
      prevStyling: styling,
      rootStyle: { ...styling, ...styles.root },
      localInputText: inputText || ''
    };
  }

  static getDerivedStateFromProps(props, state) {
    if (props.styling !== state.prevStyling) {
      const newRootStyle = { ...props.styling, ...styles.root };
      if (!isEqual(newRootStyle, state.rootStyle)) {
        return {
          prevStyling: props.styling,
          rootStyle: newRootStyle
        };
      }
    }
    return null;
  }

  shouldComponentUpdate(nextProps, nextState, nextContext) {
    const { localInputText, rootStyle } = this.state;
    const { data } = this.props;
    return (
      localInputText !== nextState.localInputText ||
      data !== nextProps.data ||
      rootStyle !== nextState.rootStyle
    );
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
    const { inputText } = this.props;
    const { localInputText } = this.state;
    if (inputText !== prevProps.inputText && localInputText !== inputText) {
      this.setState({
        localInputText: inputText || ''
      });
    }
  }

  handleChangeInputValue = e => {
    this.setState({
      localInputText: e.target.value
    });
    this.props.onInputTextChange({
      enteredText: e.target.value
    });
  };

  handleButtonClick = e => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    this.props.onSubmit({
      enteredText: this.state.localInputText
    });
  };

  render() {
    const { data, cells } = this.props;
    const { rootStyle, localInputText } = this.state;
    return (
      <MUIButton size={data.size} variant={data.variant}>{data.text}</MUIButton>
    );
  }
}

Button.propTypes = ButtonTypes;

Button.defaultProps = {
  styling: {
    padding: '1em',
    margin: '4em',
    borderColor: '#cdcdcd',
    borderWidth: '2px',
    borderStyle: 'dotted'
  },
  data: {
    text:'Button',
    size:'medium',
    color:'primary',
    variant:'contained',
  },
  cells: [<div>Placeholder</div>],
  onInputTextChange: () => {
    console.info('Button.onInputTextChange is not set');
  },
  onSubmit: () => {
    console.info('Button.onSubmit is not set');
  }
};

export default Button;
