import isEqual from "lodash/isEqual";
import React from "react";
import { testTypes } from "./test.props";

const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  containerStyle: {
    marginTop: "1em",
    marginBottom: "1em",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};

/**
 * test is generated by Webcodesk. Replace this comment with a valuable descriptions.
 */
class test extends React.Component {
  constructor(props) {
    super(props);
    const { inputText, styling } = this.props;
    this.state = {
      prevStyling: styling,
      rootStyle: { ...styling, ...styles.root },
      localInputText: inputText || "",
    };
  }

  static getDerivedStateFromProps(props, state) {
    if (props.styling !== state.prevStyling) {
      const newRootStyle = { ...props.styling, ...styles.root };
      if (!isEqual(newRootStyle, state.rootStyle)) {
        return {
          prevStyling: props.styling,
          rootStyle: newRootStyle,
        };
      }
    }
    return null;
  }

  shouldComponentUpdate(nextProps, nextState, nextContext) {
    const { localInputText, rootStyle } = this.state;
    const { data } = this.props;
    return (
      localInputText !== nextState.localInputText ||
      data !== nextProps.data ||
      rootStyle !== nextState.rootStyle
    );
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
    const { inputText } = this.props;
    const { localInputText } = this.state;
    if (inputText !== prevProps.inputText && localInputText !== inputText) {
      this.setState({
        localInputText: inputText || "",
      });
    }
  }

  handleChangeInputValue = (e) => {
    this.setState({
      localInputText: e.target.value,
    });
    this.props.onInputTextChange({
      enteredText: e.target.value,
    });
  };

  handleButtonClick = (e) => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    this.props.onSubmit({
      enteredText: this.state.localInputText,
    });
  };

  render() {
    const { data, cells } = this.props;
    const { rootStyle, localInputText } = this.state;
    return (
      <div
        style={{
          fontFamily:
            "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
          height: "82px",
          paddingBottom: "24px",
          paddingTop: "24px",
          textSizeAdjust: "100%",
          width: "800px",
          WebkitFontSmoothing: "antialiased",
        }}
        className={
          "style_px-mobile-1__DSM5j style_px-tablet-1__R5dkv style_pt-mobile-0__lBXpV style_pt-desktop-6__eNi8V style_pt-tablet-6__BJU9d style_pt-widescreen-6__SWPD_ style_pb-mobile-7__OX0Sz style_pb-desktop-6__EZ3zm style_pb-tablet-6__F61Qx style_pb-widescreen-6__UB2pW"
        }
      >
        <div
          style={{
            animationDuration: "0.3s",
            animationName: "styles_fadeIn__tu4uh",
            animationTimingFunction: "ease-in-out",
            backgroundColor: "rgb(255, 255, 255)",
            backgroundImage:
              "linear-gradient(12deg, rgb(255, 255, 255) 50%, rgba(255, 255, 255, 0))",
            boxSizing: "border-box",
            display: "flex",
            flexBasis: "0%",
            flexGrow: 1,
            fontFamily:
              "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
            transitionDuration: "0.3s",
            transitionProperty: "background-color",
            transitionTimingFunction: "ease-in",
          }}
          className={
            "styles_item__Sn_12 style_flex___KlcI style_direction-row__oinjH style_flex-row-gap-4__izJPT style_flex-row-gap-mobile-2__weEnV undefined style_flex-1__YfiEx"
          }
          data-test={"post-item-358109"}
        >
          <a
            style={{
              cursor: "pointer",
              fontFamily:
                "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
              textDecoration: "none",
            }}
            href={"/posts/hyresnap"}
          >
            <div
              style={{
                bottom: "0px",
                fontFamily:
                  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                left: "0px",
                position: "relative",
                right: "0px",
                top: "0px",
              }}
              className={"styles_thumbnail__Rmwk5 styles_thumbnail__E2_pB"}
              data-test={"post-thumbnail"}
            >
              <div
                style={{
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                }}
                className={"lazyload-wrapper"}
              >
                <img
                  style={{
                    borderBottomLeftRadius: "4px",
                    borderBottomRightRadius: "4px",
                    borderTopLeftRadius: "4px",
                    borderTopRightRadius: "4px",
                    bottom: "0px",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    left: "0px",
                    position: "relative",
                    right: "0px",
                    top: "0px",
                    verticalAlign: "bottom",
                    width: "80px",
                    zIndex: 0,
                  }}
                  srcset={
                    data.image
                  }
                  src={data.image
                  }
                  alt={"HyreSnap"}
                  className={"styles_mediaThumbnail__LDCQN"}
                ></img>
              </div>
            </div>
          </a>
          <div
            style={{
              boxSizing: "border-box",
              display: "flex",
              flexBasis: "0%",
              flexDirection: "column",
              flexGrow: 1,
              fontFamily:
                "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
              marginInlineStart: "16px",
              marginLeft: "16px",
            }}
            className={
              "style_flex___KlcI style_direction-column__w77hU style_flex-1__YfiEx"
            }
          >
            <div
              style={{
                borderBlockEndColor: "rgb(33, 41, 60)",
                borderBlockStartColor: "rgb(33, 41, 60)",
                borderBottomColor: "rgb(33, 41, 60)",
                borderInlineEndColor: "rgb(33, 41, 60)",
                borderInlineStartColor: "rgb(33, 41, 60)",
                borderLeftColor: "rgb(33, 41, 60)",
                borderRightColor: "rgb(33, 41, 60)",
                borderTopColor: "rgb(33, 41, 60)",
                caretColor: "rgb(33, 41, 60)",
                color: "rgb(33, 41, 60)",
                columnRuleColor: "rgb(33, 41, 60)",
                display: "-webkit-box",
                fontFamily:
                  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                fontWeight: 600,
                hyphens: "auto",
                lineHeight: "24px",
                outlineColor: "rgb(33, 41, 60)",
                overflowWrap: "break-word",
                overflowX: "hidden",
                overflowY: "hidden",
                textDecoration: "none solid rgb(33, 41, 60)",
                textDecorationColor: "rgb(33, 41, 60)",
                textEmphasisColor: "rgb(33, 41, 60)",
                textOverflow: "ellipsis",
                whiteSpace: "pre-line",
                wordBreak: "break-word",
                WebkitBoxOrient: "vertical",
                WebkitLineClamp: 2,
                WebkitTextFillColor: "rgb(33, 41, 60)",
                WebkitTextStrokeColor: "rgb(33, 41, 60)",
              }}
              className={
                "styles_format__w0VVk style_color-dark-grey__aN5DV style_fontSize-mobile-12__TFXTT style_fontSize-desktop-16__5wSUg style_fontSize-tablet-16__HZyhH style_fontSize-widescreen-16___dF3w style_fontWeight-600__Qmfob style_noOfLines-2__0ZXbJ"
              }
            >
              <a
                style={{
                  cursor: "pointer",
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                  textDecoration: "none",
                }}
                href={"/posts/hyresnap"}
                data-test={"post-name-358109"}
                className={"styles_title__jWi91"}
              >
                {data.title}
              </a>
            </div>
            <div
              style={{
                borderBlockEndColor: "rgb(75, 88, 124)",
                borderBlockStartColor: "rgb(75, 88, 124)",
                borderBottomColor: "rgb(75, 88, 124)",
                borderInlineEndColor: "rgb(75, 88, 124)",
                borderInlineStartColor: "rgb(75, 88, 124)",
                borderLeftColor: "rgb(75, 88, 124)",
                borderRightColor: "rgb(75, 88, 124)",
                borderTopColor: "rgb(75, 88, 124)",
                caretColor: "rgb(75, 88, 124)",
                color: "rgb(75, 88, 124)",
                columnRuleColor: "rgb(75, 88, 124)",
                display: "-webkit-box",
                fontFamily:
                  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                lineHeight: "24px",
                outlineColor: "rgb(75, 88, 124)",
                overflowX: "hidden",
                overflowY: "hidden",
                textDecoration: "none solid rgb(75, 88, 124)",
                textDecorationColor: "rgb(75, 88, 124)",
                textEmphasisColor: "rgb(75, 88, 124)",
                textOverflow: "ellipsis",
                WebkitBoxOrient: "vertical",
                WebkitLineClamp: 2,
                WebkitTextFillColor: "rgb(75, 88, 124)",
                WebkitTextStrokeColor: "rgb(75, 88, 124)",
              }}
              className={
                "style_color-light-grey__mkoQQ style_fontSize-mobile-12__TFXTT style_fontSize-desktop-16__5wSUg style_fontSize-tablet-16__HZyhH style_fontSize-widescreen-16___dF3w style_fontWeight-400__5p97M style_noOfLines-2__0ZXbJ"
              }
            >
              <a
                style={{
                  cursor: "pointer",
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                  textDecoration: "none",
                }}
                href={"/posts/hyresnap"}
                data-test={"post-358109-tagline"}
                className={"styles_tagline__j29pO"}
              >
                {data.description}
              </a>
            </div>
            <div
              style={{
                alignItems: "center",
                boxSizing: "border-box",
                display: "flex",
                fontFamily:
                  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                marginBlockStart: "12px",
                marginTop: "12px",
              }}
              className={
                "style_flex___KlcI style_direction-row__oinjH style_flex-row-gap-6__1D59d style_mt-3__RD4Rz style_align-center__76pto"
              }
            >
              <a
                style={{
                  backgroundColor: "rgb(255, 255, 255)",
                  borderBlockEndColor: "rgba(0, 0, 0, 0)",
                  borderBlockEndStyle: "solid",
                  borderBlockEndWidth: "1px",
                  borderBlockStartColor: "rgba(0, 0, 0, 0)",
                  borderBlockStartStyle: "solid",
                  borderBlockStartWidth: "1px",
                  borderBottomColor: "rgba(0, 0, 0, 0)",
                  borderBottomLeftRadius: "4px",
                  borderBottomRightRadius: "4px",
                  borderBottomStyle: "solid",
                  borderBottomWidth: "1px",
                  borderInlineEndColor: "rgba(0, 0, 0, 0)",
                  borderInlineEndStyle: "solid",
                  borderInlineEndWidth: "1px",
                  borderInlineStartColor: "rgba(0, 0, 0, 0)",
                  borderInlineStartStyle: "solid",
                  borderInlineStartWidth: "1px",
                  borderLeftColor: "rgba(0, 0, 0, 0)",
                  borderLeftStyle: "solid",
                  borderLeftWidth: "1px",
                  borderRightColor: "rgba(0, 0, 0, 0)",
                  borderRightStyle: "solid",
                  borderRightWidth: "1px",
                  borderTopColor: "rgba(0, 0, 0, 0)",
                  borderTopLeftRadius: "4px",
                  borderTopRightRadius: "4px",
                  borderTopStyle: "solid",
                  borderTopWidth: "1px",
                  bottom: "0px",
                  caretColor: "rgb(75, 88, 124)",
                  color: "rgb(75, 88, 124)",
                  columnRuleColor: "rgb(75, 88, 124)",
                  cursor: "pointer",
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                  left: "0px",
                  maxHeight: "24px",
                  outlineColor: "rgb(75, 88, 124)",
                  position: "relative",
                  right: "0px",
                  textAlign: "center",
                  textDecoration: "none",
                  textDecorationColor: "rgb(75, 88, 124)",
                  textEmphasisColor: "rgb(75, 88, 124)",
                  top: "0px",
                  transitionDuration: "0.3s",
                  WebkitTextFillColor: "rgb(75, 88, 124)",
                  WebkitTextStrokeColor: "rgb(75, 88, 124)",
                }}
                className={"styles_reset__opz7w styles_button__Pe4nq"}
                href={"/posts/hyresnap"}
              >
                <div
                  style={{
                    alignItems: "center",
                    borderBlockEndColor: "rgb(75, 88, 124)",
                    borderBlockStartColor: "rgb(75, 88, 124)",
                    borderBottomColor: "rgb(75, 88, 124)",
                    borderInlineEndColor: "rgb(75, 88, 124)",
                    borderInlineStartColor: "rgb(75, 88, 124)",
                    borderLeftColor: "rgb(75, 88, 124)",
                    borderRightColor: "rgb(75, 88, 124)",
                    borderTopColor: "rgb(75, 88, 124)",
                    boxSizing: "border-box",
                    caretColor: "rgb(75, 88, 124)",
                    color: "rgb(75, 88, 124)",
                    columnRuleColor: "rgb(75, 88, 124)",
                    display: "flex",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    outlineColor: "rgb(75, 88, 124)",
                    textDecoration: "none solid rgb(75, 88, 124)",
                    textDecorationColor: "rgb(75, 88, 124)",
                    textEmphasisColor: "rgb(75, 88, 124)",
                    WebkitTextStrokeColor: "rgb(75, 88, 124)",
                  }}
                  className={
                    "style_flex___KlcI style_direction-row__oinjH style_align-center__76pto"
                  }
                >
                  <svg
                    style={{
                      fontFamily:
                        "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                      height: "18px",
                      marginInlineEnd: "8px",
                      marginRight: "8px",
                      overflowX: "hidden",
                      overflowY: "hidden",
                      width: "12px",
                    }}
                    viewBox={"0 0 13 13"}
                    xmlns={"http://www.w3.org/2000/svg"}
                    className={"styles_icon__SI2oN"}
                  >
                    <path
                      style={{
                        fill: "rgb(75, 88, 124)",
                        fontFamily:
                          "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                      }}
                      d={
                        "M6.5.75c-3.31 0-6 2.362-6 5.267 0 2.905 2.69 5.266 6 5.266a6.8 6.8 0 0 0 1.036-.08l2.725 1.486a.5.5 0 0 0 .74-.44V9.46a4.893 4.893 0 0 0 1.5-3.443C12.5 3.112 9.81.75 6.5.75z"
                      }
                      fill={"currentColor"}
                    ></path>
                  </svg>
                  <div
                    style={{
                      fontFamily:
                        "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                      fontSize: "12px",
                      fontWeight: 600,
                      lineHeight: "20px",
                    }}
                    className={
                      "style_color-light-grey__mkoQQ style_fontSize-12__obnXo style_fontWeight-600__Qmfob"
                    }
                  >
                    {data.number1}
                  </div>
                </div>
              </a>
              <div
                style={{
                  boxSizing: "border-box",
                  display: "flex",
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                  marginInlineStart: "24px",
                  marginLeft: "24px",
                }}
                className={
                  "style_flex___KlcI style_direction-row__oinjH style_flex-row-gap-3__HVkap"
                }
              >
                <div
                  style={{
                    borderBlockEndColor: "rgb(75, 88, 124)",
                    borderBlockStartColor: "rgb(75, 88, 124)",
                    borderBottomColor: "rgb(75, 88, 124)",
                    borderInlineEndColor: "rgb(75, 88, 124)",
                    borderInlineStartColor: "rgb(75, 88, 124)",
                    borderLeftColor: "rgb(75, 88, 124)",
                    borderRightColor: "rgb(75, 88, 124)",
                    borderTopColor: "rgb(75, 88, 124)",
                    caretColor: "rgb(75, 88, 124)",
                    color: "rgb(75, 88, 124)",
                    columnRuleColor: "rgb(75, 88, 124)",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    fontSize: "12px",
                    lineHeight: "20px",
                    outlineColor: "rgb(75, 88, 124)",
                    textDecoration: "none solid rgb(75, 88, 124)",
                    textDecorationColor: "rgb(75, 88, 124)",
                    textEmphasisColor: "rgb(75, 88, 124)",
                    WebkitTextFillColor: "rgb(75, 88, 124)",
                    WebkitTextStrokeColor: "rgb(75, 88, 124)",
                  }}
                  className={
                    "style_color-light-grey__mkoQQ style_fontSize-12__obnXo style_fontWeight-400__5p97M"
                  }
                >
                  Free Options
                </div>
                <a
                  style={{
                    cursor: "pointer",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    marginInlineStart: "12px",
                    marginLeft: "12px",
                    textDecoration: "none",
                  }}
                  className={"styles_postTopicLink__wDe_p"}
                  href={"/topics/saas"}
                >
                  <div
                    style={{
                      borderBlockEndColor: "rgb(75, 88, 124)",
                      borderBlockStartColor: "rgb(75, 88, 124)",
                      borderBottomColor: "rgb(75, 88, 124)",
                      borderInlineEndColor: "rgb(75, 88, 124)",
                      borderInlineStartColor: "rgb(75, 88, 124)",
                      borderLeftColor: "rgb(75, 88, 124)",
                      borderRightColor: "rgb(75, 88, 124)",
                      borderTopColor: "rgb(75, 88, 124)",
                      caretColor: "rgb(75, 88, 124)",
                      color: "rgb(75, 88, 124)",
                      columnRuleColor: "rgb(75, 88, 124)",
                      fontFamily:
                        "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                      fontSize: "12px",
                      lineHeight: "20px",
                      outlineColor: "rgb(75, 88, 124)",
                      textDecoration: "none solid rgb(75, 88, 124)",
                      textDecorationColor: "rgb(75, 88, 124)",
                      textEmphasisColor: "rgb(75, 88, 124)",
                      WebkitTextFillColor: "rgb(75, 88, 124)",
                      WebkitTextStrokeColor: "rgb(75, 88, 124)",
                    }}
                    className={
                      "style_color-light-grey__mkoQQ style_fontSize-12__obnXo style_fontWeight-400__5p97M"
                    }
                  >
                    SaaS
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div
            style={{
              boxSizing: "border-box",
              display: "flex",
              flexDirection: "column",
              fontFamily:
                "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
              marginBlockEnd: "8px",
              marginBlockStart: "8px",
              marginBottom: "8px",
              marginInlineEnd: "8px",
              marginInlineStart: "16px",
              marginLeft: "16px",
              marginRight: "8px",
              marginTop: "8px",
            }}
            className={
              "style_flex___KlcI style_direction-column__w77hU style_mr-mobile-0__F4b_5 style_mr-desktop-2__W_BVE style_mr-tablet-2__maqcw style_mr-widescreen-2__0HngF style_mt-2__5s4E_ style_mb-2__p1e2_ style_ml-mobile-2__Blf3J style_ml-desktop-0__VafBB style_ml-tablet-0__ep9GS"
            }
          >
            <button
              style={{
                appearance: "none",
                backgroundColor: "rgb(255, 255, 255)",
                borderBlockEndColor: "rgb(217, 225, 236)",
                borderBlockEndStyle: "solid",
                borderBlockEndWidth: "1px",
                borderBlockStartColor: "rgb(217, 225, 236)",
                borderBlockStartStyle: "solid",
                borderBlockStartWidth: "1px",
                borderBottomColor: "rgb(217, 225, 236)",
                borderBottomLeftRadius: "4px",
                borderBottomRightRadius: "4px",
                borderBottomStyle: "solid",
                borderBottomWidth: "1px",
                borderInlineEndColor: "rgb(217, 225, 236)",
                borderInlineEndStyle: "solid",
                borderInlineEndWidth: "1px",
                borderInlineStartColor: "rgb(217, 225, 236)",
                borderInlineStartStyle: "solid",
                borderInlineStartWidth: "1px",
                borderLeftColor: "rgb(217, 225, 236)",
                borderLeftStyle: "solid",
                borderLeftWidth: "1px",
                borderRightColor: "rgb(217, 225, 236)",
                borderRightStyle: "solid",
                borderRightWidth: "1px",
                borderTopColor: "rgb(217, 225, 236)",
                borderTopLeftRadius: "4px",
                borderTopRightRadius: "4px",
                borderTopStyle: "solid",
                borderTopWidth: "1px",
                bottom: "0px",
                cursor: "pointer",
                fontFamily:
                  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                fontSize: "16px",
                left: "0px",
                maxHeight: "64px",
                maxWidth: "52px",
                minInlineSize: "52px",
                minWidth: "52px",
                paddingBottom: "12px",
                paddingLeft: "4px",
                paddingRight: "4px",
                paddingTop: "7px",
                position: "relative",
                right: "0px",
                top: "0px",
                transitionDuration: "0.3s",
              }}
              type={"button"}
              data-test={"vote-button"}
              className={"styles_reset__opz7w styles_feed__JnsOv"}
            >
              <div
                style={{
                  alignItems: "center",
                  bottom: "0px",
                  boxSizing: "border-box",
                  display: "flex",
                  flexDirection: "column",
                  fontFamily:
                    "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                  fontSize: "16px",
                  left: "0px",
                  position: "relative",
                  right: "0px",
                  top: "0px",
                  zIndex: 3,
                }}
                className={
                  "style_flex___KlcI style_direction-column__w77hU style_align-center__76pto"
                }
              >
                <div
                  style={{
                    backgroundImage:
                      "url(https://ph-static.imgix.net/upvote-burst-light-grey-v6.png?format=auto&auto=compress)",
                    backgroundPosition: "0px 50%",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "2900%",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    height: "26px",
                    width: "45px",
                  }}
                  className={"styles_icon___8PK0 styles_lightGrey__b_fhT"}
                ></div>
                <div
                  style={{
                    borderBlockEndColor: "rgb(75, 88, 124)",
                    borderBlockStartColor: "rgb(75, 88, 124)",
                    borderBottomColor: "rgb(75, 88, 124)",
                    borderInlineEndColor: "rgb(75, 88, 124)",
                    borderInlineStartColor: "rgb(75, 88, 124)",
                    borderLeftColor: "rgb(75, 88, 124)",
                    borderRightColor: "rgb(75, 88, 124)",
                    borderTopColor: "rgb(75, 88, 124)",
                    caretColor: "rgb(75, 88, 124)",
                    color: "rgb(75, 88, 124)",
                    columnRuleColor: "rgb(75, 88, 124)",
                    fontFamily:
                      "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
                    fontSize: "12px",
                    fontWeight: 600,
                    lineHeight: "20px",
                    outlineColor: "rgb(75, 88, 124)",
                    textDecoration: "none solid rgb(75, 88, 124)",
                    textDecorationColor: "rgb(75, 88, 124)",
                    textEmphasisColor: "rgb(75, 88, 124)",
                    WebkitTextFillColor: "rgb(75, 88, 124)",
                    WebkitTextStrokeColor: "rgb(75, 88, 124)",
                  }}
                  className={
                    "style_color-light-grey__mkoQQ style_fontSize-12__obnXo style_fontWeight-600__Qmfob"
                  }
                >
                  {data.number2}
                </div>
              </div>
            </button>
          </div>
        </div>
      </div>
    );
  }
}

test.propTypes = testTypes;

test.defaultProps = {
  styling: {
    padding: "1em",
    margin: "4em",
    borderColor: "#cdcdcd",
    borderWidth: "2px",
    borderStyle: "dotted",
  },
  data: {
    image: "https://ph-files.imgix.net/216fd945-fbf3-4239-9e8e-ad567a9ae995.png",
    // Component title value
    title: "HyreSnap",
    // Placeholder text in the input element
    description: "Get the perfect resume for your next job in 10 minutes",
    number1: 546,
    number2: 152,
  },
  cells: [<div>Placeholder</div>],
  onInputTextChange: () => {
    console.info("test.onInputTextChange is not set");
  },
  onSubmit: () => {
    console.info("test.onSubmit is not set");
  },
};

export default test;
