import isEqual from 'lodash/isEqual';
import React from 'react';
import { test4Types } from './test4.props';

const styles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  },
  containerStyle: {
    marginTop: '1em',
    marginBottom: '1em',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center'
  }
};

/**
 * test4 is generated by Webcodesk. Replace this comment with a valuable description.
 */
class test4 extends React.Component {
  constructor(props) {
    super(props);
    const { inputText, styling } = this.props;
    this.state = {
      prevStyling: styling,
      rootStyle: { ...styling, ...styles.root },
      localInputText: inputText || ''
    };
  }

  static getDerivedStateFromProps(props, state) {
    if (props.styling !== state.prevStyling) {
      const newRootStyle = { ...props.styling, ...styles.root };
      if (!isEqual(newRootStyle, state.rootStyle)) {
        return {
          prevStyling: props.styling,
          rootStyle: newRootStyle
        };
      }
    }
    return null;
  }

  shouldComponentUpdate(nextProps, nextState, nextContext) {
    const { localInputText, rootStyle } = this.state;
    const { data } = this.props;
    return (
      localInputText !== nextState.localInputText ||
      data !== nextProps.data ||
      rootStyle !== nextState.rootStyle
    );
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
    const { inputText } = this.props;
    const { localInputText } = this.state;
    if (inputText !== prevProps.inputText && localInputText !== inputText) {
      this.setState({
        localInputText: inputText || ''
      });
    }
  }

  handleChangeInputValue = e => {
    this.setState({
      localInputText: e.target.value
    });
    this.props.onInputTextChange({
      enteredText: e.target.value
    });
  };

  handleButtonClick = e => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    this.props.onSubmit({
      enteredText: this.state.localInputText
    });
  };

  render() {
    const { data, cells } = this.props;
    const { rootStyle, localInputText } = this.state;
    return (
<div style={{borderBlockEndColor: 'rgb(36, 41, 47)', borderBlockStartColor: 'rgb(36, 41, 47)', borderBottomColor: 'rgb(36, 41, 47)', borderInlineEndColor: 'rgb(36, 41, 47)', borderInlineStartColor: 'rgb(36, 41, 47)', borderLeftColor: 'rgb(36, 41, 47)', borderRightColor: 'rgb(36, 41, 47)', borderTopColor: 'rgb(36, 41, 47)', bottom: '0px', boxSizing: 'border-box', caretColor: 'rgb(36, 41, 47)', color: 'rgb(36, 41, 47)', columnRuleColor: 'rgb(36, 41, 47)', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', fontSize: '14px', height: '72px', left: '0px', lineHeight: '21px', outlineColor: 'rgb(36, 41, 47)', overflowWrap: 'break-word', position: 'relative', right: '0px', textDecoration: 'none solid rgb(36, 41, 47)', textDecorationColor: 'rgb(36, 41, 47)', textEmphasisColor: 'rgb(36, 41, 47)', textSizeAdjust: '100%', top: '0px', width: '1903px', WebkitTextFillColor: 'rgb(36, 41, 47)', WebkitTextStrokeColor: 'rgb(36, 41, 47)'}} className = {"position-relative js-header-wrapper "} >
      <a style={{backgroundColor: 'rgb(9, 105, 218)', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', bottom: '24px', boxSizing: 'border-box', caretColor: 'rgb(255, 255, 255)', clip: 'rect(1px, 1px, 1px, 1px)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', cursor: 'pointer', display: 'block', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', height: '48px', insetBlockEnd: '24px', insetInlineEnd: '1887px', left: '0px', outlineColor: 'rgb(255, 255, 255)', overflowX: 'hidden', overflowY: 'hidden', paddingBottom: '24px', paddingLeft: '8px', paddingRight: '8px', paddingTop: '24px', position: 'absolute', right: '1887px', textDecoration: 'none', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', top: '0px', width: '16px', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} href = {"#start-of-content"} className = {"px-2 py-4 color-bg-accent-emphasis color-fg-on-emphasis show-on-focus js-skip-to-content"} >Skip to content</a>
            
      


        

            <script style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} crossorigin = {"anonymous"} defer = {"defer"} type = {"application/javascript"} src = {"https://github.githubassets.com/assets/vendors-node_modules_github_remote-form_dist_index_js-node_modules_delegated-events_dist_inde-94fd67-417231a98525.js"} ></script>
<script style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} crossorigin = {"anonymous"} defer = {"defer"} type = {"application/javascript"} src = {"https://github.githubassets.com/assets/sessions-319092af3d33.js"} ></script>
<header style={{backgroundColor: 'rgb(36, 41, 47)', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', bottom: '0px', boxSizing: 'border-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', fontSize: '16px', left: '0px', lineHeight: '24px', outlineColor: 'rgb(255, 255, 255)', paddingBottom: '8px', paddingTop: '8px', position: 'relative', right: '0px', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', top: '0px', zIndex: 32, WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} className = {"Header-old header-logged-out js-details-container Details position-relative f4 py-2"} role = {"banner"} >
  <div style={{alignItems: 'center', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', marginInlineEnd: '311.5px', marginInlineStart: '311.5px', marginLeft: '311.5px', marginRight: '311.5px', maxWidth: '1280px', paddingLeft: '16px', paddingRight: '16px'}} className = {"container-xl d-lg-flex flex-items-center p-responsive"} >
    <div style={{alignItems: 'center', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', justifyContent: 'space-between'}} className = {"d-flex flex-justify-between flex-items-center"} >
      <a style={{boxSizing: 'border-box', cursor: 'pointer', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', marginInlineEnd: '24px', marginRight: '24px', textDecoration: 'none'}} className = {"mr-4 color-fg-inherit"} href = {"https://github.com/"} aria-label = {"Homepage"} data-ga-click = {"(Logged out) Header, go to homepage, icon:logo-wordmark"} >
        <svg style={{boxSizing: 'border-box', display: 'inline-block', fill: 'rgb(255, 255, 255)', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', verticalAlign: 'text-bottom'}} height = {32} aria-hidden = {"true"} viewBox = {"0 0 16 16"} version = {"1.1"} width = {32} data-view-component = {"true"} className = {"octicon octicon-mark-github"} >
    <path style={{boxSizing: 'border-box', fillRule: 'evenodd', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} fill-rule = {"evenodd"} d = {"M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"} ></path>
</svg>
      </a>

        

      <div style={{alignItems: 'center', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} className = {"d-flex flex-items-center"} >
            

                </div>
    </div>

    <div style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', flexGrow: 1, fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', justifyContent: 'space-between', left: '0px', maxHeight: '100%', position: 'relative', right: '0px', top: '0px', zIndex: 100}} className = {"HeaderMenu HeaderMenu--logged-out position-fixed top-0 right-0 bottom-0 height-fit position-lg-relative d-lg-flex flex-justify-between flex-items-center flex-auto"} >
      

        <nav style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} className = {"mt-0 px-3 px-lg-0 mb-5 mb-lg-0"} aria-label = {"Global"} >
          <ul style={{boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', listStyleType: 'none', marginBlockEnd: '0px', marginBlockStart: '0px', marginBottom: '0px', marginTop: '0px', paddingLeft: '0px'}} className = {"d-lg-flex list-style-none"} >
              <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <details style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} className = {"HeaderMenu-details details-overlay details-reset width-full"} >
      <summary style={{boxSizing: 'border-box', cursor: 'pointer', display: 'inline-block', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', listStylePosition: 'outside', listStyleType: 'none', paddingBottom: '16px', paddingTop: '16px', transitionDuration: '0.08s', transitionProperty: 'color, background-color, box-shadow, border-color', transitionTimingFunction: 'cubic-bezier(0.33, 1, 0.68, 1)', whiteSpace: 'nowrap'}} className = {"HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block"} >
        Product
        <svg style={{bottom: '2px', boxSizing: 'border-box', fill: 'none', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', height: '6.84375px', insetBlockEnd: '2px', insetBlockStart: '-2px', left: '0px', overflowX: 'hidden', overflowY: 'hidden', position: 'relative', right: '0px', stroke: 'rgba(255, 255, 255, 0.5)', top: '-2px', transitionDuration: '0.4s', transitionProperty: 'stroke', width: '12px'}} x = {0} y = {0} viewBox = {"0 0 14 8"} xml:space = {"preserve"} fill = {"none"} className = {"icon-chevon-down-mktg position-absolute position-lg-relative"} ><path style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} d = {"M1,1l6.2,6L13,1"} ></path></svg>
      </summary>
      
    </details>
</li>


              <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <a style={{boxSizing: 'border-box', cursor: 'pointer', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', paddingBottom: '16px', paddingTop: '16px', textDecoration: 'none', transitionDuration: '0.4s', transitionProperty: 'opacity', whiteSpace: 'nowrap'}} className = {"HeaderMenu-link no-underline py-3 d-block d-lg-inline-block"} data-analytics-event = {"{"category":"Header menu top item (logged out)","action":"click to go to Team","label":"ref_page:/webcodesk/webcodesk-srv/projects;ref_cta:Team;"}"} href = {"/team"} >Team</a>
</li>

              <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <a style={{boxSizing: 'border-box', cursor: 'pointer', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', paddingBottom: '16px', paddingTop: '16px', textDecoration: 'none', transitionDuration: '0.4s', transitionProperty: 'opacity', whiteSpace: 'nowrap'}} className = {"HeaderMenu-link no-underline py-3 d-block d-lg-inline-block"} data-analytics-event = {"{"category":"Header menu top item (logged out)","action":"click to go to Enterprise","label":"ref_page:/webcodesk/webcodesk-srv/projects;ref_cta:Enterprise;"}"} href = {"/enterprise"} >Enterprise</a>
</li>


            <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <details style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} className = {"HeaderMenu-details details-overlay details-reset width-full"} >
      <summary style={{boxSizing: 'border-box', cursor: 'pointer', display: 'inline-block', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', listStylePosition: 'outside', listStyleType: 'none', paddingBottom: '16px', paddingTop: '16px', transitionDuration: '0.08s', transitionProperty: 'color, background-color, box-shadow, border-color', transitionTimingFunction: 'cubic-bezier(0.33, 1, 0.68, 1)', whiteSpace: 'nowrap'}} className = {"HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block"} >
        Explore
        <svg style={{bottom: '2px', boxSizing: 'border-box', fill: 'none', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', height: '6.84375px', insetBlockEnd: '2px', insetBlockStart: '-2px', left: '0px', overflowX: 'hidden', overflowY: 'hidden', position: 'relative', right: '0px', stroke: 'rgba(255, 255, 255, 0.5)', top: '-2px', transitionDuration: '0.4s', transitionProperty: 'stroke', width: '12px'}} x = {0} y = {0} viewBox = {"0 0 14 8"} xml:space = {"preserve"} fill = {"none"} className = {"icon-chevon-down-mktg position-absolute position-lg-relative"} ><path style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} d = {"M1,1l6.2,6L13,1"} ></path></svg>
      </summary>
      
    </details>
</li>


            <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <a style={{boxSizing: 'border-box', cursor: 'pointer', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', paddingBottom: '16px', paddingTop: '16px', textDecoration: 'none', transitionDuration: '0.4s', transitionProperty: 'opacity', whiteSpace: 'nowrap'}} className = {"HeaderMenu-link no-underline py-3 d-block d-lg-inline-block"} data-analytics-event = {"{"category":"Header menu top item (logged out)","action":"click to go to Marketplace","label":"ref_page:/webcodesk/webcodesk-srv/projects;ref_cta:Marketplace;"}"} href = {"/marketplace"} >Marketplace</a>
</li>


            <li style={{alignItems: 'center', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', justifyContent: 'space-between', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"} >
    <details style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} className = {"HeaderMenu-details details-overlay details-reset width-full"} >
      <summary style={{boxSizing: 'border-box', cursor: 'pointer', display: 'inline-block', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', listStylePosition: 'outside', listStyleType: 'none', paddingBottom: '16px', paddingTop: '16px', transitionDuration: '0.08s', transitionProperty: 'color, background-color, box-shadow, border-color', transitionTimingFunction: 'cubic-bezier(0.33, 1, 0.68, 1)', whiteSpace: 'nowrap'}} className = {"HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block"} >
        Pricing
        <svg style={{bottom: '2px', boxSizing: 'border-box', fill: 'none', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', height: '6.84375px', insetBlockEnd: '2px', insetBlockStart: '-2px', left: '0px', overflowX: 'hidden', overflowY: 'hidden', position: 'relative', right: '0px', stroke: 'rgba(255, 255, 255, 0.5)', top: '-2px', transitionDuration: '0.4s', transitionProperty: 'stroke', width: '12px'}} x = {0} y = {0} viewBox = {"0 0 14 8"} xml:space = {"preserve"} fill = {"none"} className = {"icon-chevon-down-mktg position-absolute position-lg-relative"} ><path style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} d = {"M1,1l6.2,6L13,1"} ></path></svg>
      </summary>
      
    </details>
</li>

          </ul>
        </nav>

      <div style={{alignItems: 'center', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', textAlign: 'left'}} className = {"d-lg-flex flex-items-center px-3 px-lg-0 text-center text-lg-left"} >
          <div style={{boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', minInlineSize: '0px', minWidth: '0px'}} className = {"d-lg-flex min-width-0 mb-3 mb-lg-0"} >
            



<div style={{bottom: '0px', boxSizing: 'border-box', flexGrow: 1, fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', left: '0px', marginInlineEnd: '16px', marginRight: '16px', maxWidth: '272px', position: 'relative', right: '0px', top: '0px', transitionDuration: '0.2s', transitionProperty: 'max-width, padding-bottom, padding-top', transitionTimingFunction: 'ease-in-out', width: '240px'}} className = {"header-search flex-auto js-site-search position-relative flex-self-stretch flex-md-self-auto mb-3 mb-md-0 mr-0 mr-md-3 scoped-search site-scoped-search js-jump-to"} >
  <div style={{bottom: '0px', boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', left: '0px', position: 'relative', right: '0px', top: '0px'}} className = {"position-relative"} >
    <form style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', marginBlockEnd: '0px', marginBottom: '0px'}} className = {"js-site-search-form"} role = {"search"} aria-label = {"Site"} data-scope-type = {"Repository"} data-scope-id = {220029993} data-scoped-search-url = {"/webcodesk/webcodesk-srv/search"} data-owner-scoped-search-url = {"/orgs/webcodesk/search"} data-unscoped-search-url = {"/search"} data-turbo = {"false"} action = {"/webcodesk/webcodesk-srv/search"} accept-charset = {"UTF-8"} method = {"get"} >
      <label style={{alignItems: 'center', backgroundColor: 'rgb(36, 41, 47)', backgroundPosition: 'right 8px 50%', backgroundRepeat: 'no-repeat', borderBlockEndColor: 'rgb(87, 96, 106)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '1px', borderBlockStartColor: 'rgb(87, 96, 106)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '1px', borderBottomColor: 'rgb(87, 96, 106)', borderBottomLeftRadius: '6px', borderBottomRightRadius: '6px', borderBottomStyle: 'solid', borderBottomWidth: '1px', borderInlineEndColor: 'rgb(87, 96, 106)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '1px', borderInlineStartColor: 'rgb(87, 96, 106)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '1px', borderLeftColor: 'rgb(87, 96, 106)', borderLeftStyle: 'solid', borderLeftWidth: '1px', borderRightColor: 'rgb(87, 96, 106)', borderRightStyle: 'solid', borderRightWidth: '1px', borderTopColor: 'rgb(87, 96, 106)', borderTopLeftRadius: '6px', borderTopRightRadius: '6px', borderTopStyle: 'solid', borderTopWidth: '1px', bottom: '0px', boxSizing: 'border-box', display: 'flex', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', justifyContent: 'space-between', left: '0px', lineHeight: '20px', maxWidth: '100%', minBlockSize: '28px', minHeight: '28px', position: 'relative', right: '0px', top: '0px', transitionDuration: '0.08s', transitionProperty: 'color, background-color, box-shadow, border-color', transitionTimingFunction: 'cubic-bezier(0.33, 1, 0.68, 1)', verticalAlign: 'middle'}} className = {"form-control input-sm header-search-wrapper p-0 js-chromeless-input-container header-search-wrapper-jump-to position-relative d-flex flex-justify-between flex-items-center"} >
        <input style={{appearance: 'none', backgroundColor: 'rgba(0, 0, 0, 0)', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockEndStyle: 'none', borderBlockEndWidth: '0px', borderBlockStartColor: 'rgb(255, 255, 255)', borderBlockStartStyle: 'none', borderBlockStartWidth: '0px', borderBottomColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '6px', borderBottomRightRadius: '6px', borderBottomStyle: 'none', borderBottomWidth: '0px', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineEndStyle: 'none', borderInlineEndWidth: '0px', borderInlineStartColor: 'rgb(255, 255, 255)', borderInlineStartStyle: 'none', borderInlineStartWidth: '0px', borderLeftColor: 'rgb(255, 255, 255)', borderLeftStyle: 'none', borderLeftWidth: '0px', borderRightColor: 'rgb(255, 255, 255)', borderRightStyle: 'none', borderRightWidth: '0px', borderTopColor: 'rgb(255, 255, 255)', borderTopLeftRadius: '6px', borderTopRightRadius: '6px', borderTopStyle: 'none', borderTopWidth: '0px', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', fontSize: '14px', lineHeight: '20px', minBlockSize: '28px', minHeight: '28px', outlineColor: 'rgb(255, 255, 255)', paddingBottom: '8px', paddingLeft: '12px', paddingRight: '12px', paddingTop: '8px', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', transitionDuration: '0.08s', transitionProperty: 'color, background-color, box-shadow, border-color', transitionTimingFunction: 'cubic-bezier(0.33, 1, 0.68, 1)', verticalAlign: 'middle', width: '210.797px'}} type = {"text"} className = {"form-control input-sm header-search-input jump-to-field js-jump-to-field js-site-search-focus js-site-search-field is-clearable"} data-hotkey = {"s,/"} data-test-selector = {"nav-search-input"} placeholder = {"Search"} data-unscoped-placeholder = {"Search GitHub"} data-scoped-placeholder = {"Search"} autoCapitalize = {"off"} role = {"combobox"} aria-haspopup = {"listbox"} aria-expanded = {"false"} aria-autocomplete = {"list"} aria-controls = {"jump-to-results"} aria-label = {"Search"} data-jump-to-suggestions-path = {"/_graphql/GetSuggestedNavigationDestinations"} spellcheck = {"false"} autoComplete = {"off"} ></input>
        
        
            <svg style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', height: '20px', marginInlineEnd: '8px', marginRight: '8px', overflowX: 'hidden', overflowY: 'hidden'}} xmlns = {"http://www.w3.org/2000/svg"} width = {22} height = {20} aria-hidden = {"true"} className = {"mr-1 header-search-key-slash"} ><path style={{boxSizing: 'border-box', fill: 'none', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', opacity: '0.4', stroke: 'rgb(151, 154, 156)'}} fill = {"none"} stroke = {"#979A9C"} opacity = {".4"} d = {"M3.5.5h12c1.7 0 3 1.3 3 3v13c0 1.7-1.3 3-3 3h-12c-1.7 0-3-1.3-3-3v-13c0-1.7 1.3-3 3-3z"} ></path><path style={{boxSizing: 'border-box', fill: 'rgb(151, 154, 156)', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji'}} fill = {"#979A9C"} d = {"M11.8 6L8 15.1h-.9L10.8 6h1z"} ></path></svg>


          
      </label>
</form>  </div>
</div>

          </div>

        <div style={{bottom: '0px', boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', insetInlineEnd: '0px', left: '0px', marginInlineEnd: '16px', marginRight: '16px', position: 'relative', right: '0px', top: '0px'}} className = {"position-relative mr-3 mb-4 mb-lg-0 d-inline-block"} >
          <a style={{boxSizing: 'border-box', cursor: 'pointer', flexShrink: 0, fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', textDecoration: 'none', transitionDuration: '0.4s', transitionProperty: 'opacity', whiteSpace: 'nowrap'}} href = {"/login?return_to=https%3A%2F%2Fgithub.com%2Fwebcodesk%2Fwebcodesk-srv%2Fprojects"} className = {"HeaderMenu-link flex-shrink-0 no-underline"} data-hydro-click = {"{"event_type":"authentication.click","payload":{"location_in_page":"site header menu","repository_id":null,"auth_type":"SIGN_UP","originating_url":"https://github.com/webcodesk/webcodesk-srv/projects","user_id":null}}"} data-hydro-click-hmac = {"a63b16d3378e64f57f57277c172f1ca3c41c1748791f098d631a8e8549560a9c"} data-ga-click = {"(Logged out) Header, clicked Sign in, text:sign-in"} >
            Sign in
          </a>
        </div>

          <a style={{borderBlockEndColor: 'rgb(208, 215, 222)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '1px', borderBlockStartColor: 'rgb(208, 215, 222)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '1px', borderBottomColor: 'rgb(208, 215, 222)', borderBottomLeftRadius: '6px', borderBottomRightRadius: '6px', borderBottomStyle: 'solid', borderBottomWidth: '1px', borderInlineEndColor: 'rgb(208, 215, 222)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '1px', borderInlineStartColor: 'rgb(208, 215, 222)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '1px', borderLeftColor: 'rgb(208, 215, 222)', borderLeftStyle: 'solid', borderLeftWidth: '1px', borderRightColor: 'rgb(208, 215, 222)', borderRightStyle: 'solid', borderRightWidth: '1px', borderTopColor: 'rgb(208, 215, 222)', borderTopLeftRadius: '6px', borderTopRightRadius: '6px', borderTopStyle: 'solid', borderTopWidth: '1px', boxSizing: 'border-box', cursor: 'pointer', flexShrink: 0, fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji', paddingBottom: '4px', paddingLeft: '8px', paddingRight: '8px', paddingTop: '4px', textDecoration: 'none', transitionDuration: '0.4s', transitionProperty: 'opacity', whiteSpace: 'nowrap'}} href = {"/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F%3Cuser-name%3E%2F%3Crepo-name%3E%2Frepos%2Fmemexes%2Findex&source=header-repo&source_repo=webcodesk%2Fwebcodesk-srv"} className = {"HeaderMenu-link flex-shrink-0 d-inline-block no-underline border color-border-default rounded px-2 py-1"} data-hydro-click = {"{"event_type":"authentication.click","payload":{"location_in_page":"site header menu","repository_id":null,"auth_type":"SIGN_UP","originating_url":"https://github.com/webcodesk/webcodesk-srv/projects","user_id":null}}"} data-hydro-click-hmac = {"a63b16d3378e64f57f57277c172f1ca3c41c1748791f098d631a8e8549560a9c"} data-analytics-event = {"{"category":"Sign up","action":"click to sign up for account","label":"ref_page:/<user-name>/<repo-name>/repos/memexes/index;ref_cta:Sign up;ref_loc:header logged out"}"} >
            Sign up
          </a>
      </div>
    </div>
  </div>
</header>

    </div>
    );
  }
}

test4.propTypes = test4Types;

test4.defaultProps = {
  styling: {
    padding: '1em',
    margin: '4em',
    borderColor: '#cdcdcd',
    borderWidth: '2px',
    borderStyle: 'dotted'
  },
  data: {
    title: 'Empty Title Value',
    placeholder: 'Enter text',
    inputText: '',
    inputObject: {},
    inputArray: []
  },
  cells: [<div>Placeholder</div>],
  onInputTextChange: () => {
    console.info('test4.onInputTextChange is not set');
  },
  onSubmit: () => {
    console.info('test4.onSubmit is not set');
  }
};

export default test4;
